'use client';

import { useState } from 'react';
import { Icon } from 'xtreme-ui';

import { TTable } from '#utils/database/models/table';
import QRCodeComponent from '#components/base/QRCode';
import Modal from './Modal';
import './qrCodeModal.scss';

interface QRCodeModalProps {
	open: boolean;
	setOpen: (open: boolean) => void;
	table: TTable | null;
}

const QRCodeModal = ({ open, setOpen, table }: QRCodeModalProps) => {
	const [qrSize, setQrSize] = useState(300);

	if (!table) return null;

	const qrData = `${typeof window !== 'undefined' ? window.location.origin : ''}/scan?restaurant=${table.restaurantID}&table=${table.username}`;

	const downloadQR = () => {
		const canvas = document.querySelector('.qr-code-canvas') as HTMLCanvasElement;
		if (canvas) {
			const link = document.createElement('a');
			link.download = `table-${table.tableNumber}-qr.png`;
			link.href = canvas.toDataURL();
			link.click();
		}
	};

	const printQR = () => {
		const printWindow = window.open('', '_blank');
		if (printWindow) {
			printWindow.document.write(`
				<html>
					<head>
						<title>Table ${table.tableNumber} QR Code</title>
						<style>
							body { 
								font-family: Arial, sans-serif; 
								text-align: center; 
								padding: 20px;
							}
							.qr-container { 
								display: inline-block; 
								border: 2px solid #333; 
								padding: 20px; 
								border-radius: 10px;
							}
							.table-info { 
								margin-bottom: 20px; 
								font-size: 18px;
							}
							canvas { 
								display: block; 
								margin: 0 auto; 
							}
						</style>
					</head>
					<body>
						<div class="qr-container">
							<div class="table-info">
								<h2>${table.name}</h2>
								<p>Table #${table.tableNumber}</p>
								<p>Capacity: ${table.capacity} people</p>
							</div>
							<canvas width="${qrSize}" height="${qrSize}"></canvas>
						</div>
						<script>
							// Generate QR code in print window
							fetch('${qrData}')
								.then(response => response.text())
								.then(() => {
									// QR code will be generated by the canvas element
									setTimeout(() => window.print(), 500);
								});
						</script>
					</body>
				</html>
			`);
			printWindow.document.close();
		}
	};

	return (
		<Modal open={open} setOpen={setOpen}>
			<div className='qrCodeModal'>
				<div className='modalHeader'>
					<h3>QR Code for {table.name}</h3>
					<button className='closeButton' onClick={() => setOpen(false)}>
						<Icon code='f00d' size={20} />
					</button>
				</div>

				<div className='tableInfo'>
					<div className='infoItem'>
						<span className='label'>Table Number:</span>
						<span className='value'>#{table.tableNumber}</span>
					</div>
					<div className='infoItem'>
						<span className='label'>Capacity:</span>
						<span className='value'>{table.capacity} people</span>
					</div>
					<div className='infoItem'>
						<span className='label'>Status:</span>
						<span className={`status ${table.status}`}>{table.status}</span>
					</div>
				</div>

				<div className='qrContainer'>
					<QRCodeComponent 
						data={qrData} 
						size={qrSize} 
						className='qr-code-canvas'
					/>
				</div>

				<div className='qrData'>
					<label>QR Code Data:</label>
					<code>{qrData}</code>
				</div>

				<div className='sizeControl'>
					<label>QR Code Size:</label>
					<input
						type='range'
						min='200'
						max='500'
						step='50'
						value={qrSize}
						onChange={(e) => setQrSize(parseInt(e.target.value))}
					/>
					<span>{qrSize}px</span>
				</div>

				<div className='actions'>
					<button className='downloadButton' onClick={downloadQR}>
						<Icon code='f019' size={16} />
						Download
					</button>
					<button className='printButton' onClick={printQR}>
						<Icon code='f02f' size={16} />
						Print
					</button>
				</div>

				<div className='instructions'>
					<h4>Instructions:</h4>
					<ul>
						<li>Print this QR code and place it on the table</li>
						<li>Customers can scan it with their phone camera</li>
						<li>They will be redirected to your restaurant's menu</li>
						<li>Orders will be automatically associated with this table</li>
					</ul>
				</div>
			</div>
		</Modal>
	);
};

export default QRCodeModal;
